export const TerminalCommands = {
  list: ["> about", "> help", "> version","> work", "> skills", "> hobbies"],
  version: ["> Software Developer", "> Gamer", "> Electrical Engineer"],
  about: [
    "👨‍💻 Hi, I am Yash, a passionate software developer with a knack for turning complex code into elegant solutions. With a degree in electrical engineering, I bring a unique blend of technical skills and creative problem-solving to the world of software development.🕹️ When I am not immersed in lines of code, you will often find me exploring virtual worlds and mastering various gaming realms. Gaming isn it just a pastime for me; it is a way to unwind, learn strategy, and connect with friends online.",
  ],
  hobbies: ["> gaming", "> music"],
  work: ["Frontend developer at copods | APRIL 2022 - PRESENT"],
  help: [
    "> run list to find all available commands",
    "> run clear to clear all commands from the terminal",
  ],
  skills: [
    "> javascript",
    "> typescript",
    "> html",
    "> css",
    "> react.js",
    "> remix.js",
    "> next.js",
    "> meteor.js",
    "> prisma",
    "> mognoDB",
    "> supabase",
    "> aws",
    "> cypress",
    "> tailwind",
    "> webflow",
    "> wordpress",
    "> docker",
  ],
};
